name: gs
channels:
  - conda-forge
  - defaults
dependencies:
  - plyfile=0.8.1
  - python=3.7.13
  - pip=22.3.1
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn

# conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch
